# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200323_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditypricehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharepricehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
