# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-03 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_usercreditamount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCreditAmount',
            new_name='Wallet',
        ),
    ]
