# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200603_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
