# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-02 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredit',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCredit',
        ),
    ]
